### ISSUE TITLE
Implementing the `redo` pattern

### ISSUE THREAD

**Issue by kaldras** [projectcaluma/caluma#1510]
The `redo` pattern (see http://workflowpatterns.com/patterns/resource/detour/wrp34.php) would allow already finished `workItems` to be reopened and change the course of action from this point. This would be mostly beneficial for `workItems` which are associated with a `childCase` or a `taskForm` since you want to edit/modify this specific data on the `workItem` and not create a new `workItem` with an empty data set or copy the previous generated data to the new one.

**Comment by winged** [comment]
Thought about this for a bit. I'm trying to remember when we discussed this in person - some issues were mentioned, but it is not clear yet how the implementation should proceed.


### Validation & configuration

Some validation / information needs to be provided in the workflow configuration that defines which work items can be redone, as obviously we don't want everybody to be able to trigger a redo. While the validation of the proposed `RedoWorkItem` mutation can be controlled by the custom validation layer that we have in the backend, The frontend will need to know when a redo operation can be presented.

Thus, we need a `redoable` field that operates on a work item and tells us "when in work item X, with state Y, you can redo work item Z". This may be done via a JEXL expression. Since `Task`s may be reused in different workflows, this would likely need to be placed on the `TaskFlow` model, so that it can be configured depending on the workflow.

### `redoable` JEXL

While in most cases, the `redoable` field will be a static list of task slugs, we need to consider that this may be a more complex decision. We need to provide the JEXL expression with, at the minimum, the current work item. To make the decision even more extensible, we may need to provide a way to call Python code, similar to the dynamic groups feature. This may however be postponed to a later version.

### State management

As the following diagram shows, when redoing a previous work item, all work items that follow the to-be-redone work item need to be marked in a specific way. The work item that we revert to will be marked `READY`, but the follow-up ones need a new state: We can't mark them `READY` yet, an no other status option provides enough information to implement the process. We don't want them to be re-created once that redone work item is completed, as this would lead to duplicate and potentially conflicting data. We also don't want to delete them, as they may contain useful information and work results.
![image](https://user-images.githubusercontent.com/303759/125060612-d5bf1a80-e0ac-11eb-918b-b739e7d1b82e.png)

There is an implied situation where the process may take another path the second time around, for example if a circulation isn't re-done in the same way. We need to think about whether we can leave them in the `REDO` state or whether we want to re-set them back to `COMPLETED` once it's obvious they're not being re-run.
