### ISSUE TITLE
`Undo` pattern

### ISSUE THREAD

**Issue by kaldras** [projectcaluma/caluma#1511]
Sometime it would be useful to `undo` a user action (a created `workItem`) to prevent a wrong state in the workflow and clean up useless data which could lead to false conclusions since `cancel` is not the same as `undo`. I couldn't find an official pattern on http://workflowpatterns.com . Probably the following steps should be done to achieve an undo:

* Delete the `workItem` which should be undone
* Restore the previous `workItems` to their initial state

Any thoughts on this?

**Comment by winged** [comment]
I think we need to discuss which operations can be undone. The side effects of any given action may not be obviously reversible if it implies more than deleting already-created work items.

### Undoable operations:

* `CompleteWorkItem`: This may trigger followup work items, which may already be worked on. Do we support recursive undo, where the following work items are undone as well, or are we restricting ourselves to a single level of undo (Frontend may still be able to issue multiple undo calls)?
* `CreateWorkItem`: This may be easily possible, but do we need to safeguard against "undoing" a workitem that wasn't created explicitly?

Are there further operations that should be undoable?

### Side effects

Do we have other side effects when undoing an operation besides deleting a work item and potentially restoring status of the preceding workitem(s)?

### Discussion

We're discussing two different use cases here - not sure if they should be implemented by the same operation types: Undoing a "mistake" and fixing an invalid workflow state. The former may arise due to user error, the latter should be prevented by the system (validation, etc) and may need administrative action instead of an user-facing functionality

**Comment by winged** [comment]
Given the current use case, we're putting this on ice for now. The main goal was to clean up the data structure for permission/visibility purposes.

However, we now think than "undoing" a workitem creation (for example, inviting somebody onto a case that shouldn't have) is solved better by cancelling the work item than deleting it and potentially restoring some previous state. The use case (permissions/visibilities) can still be achieved by filtering the workitems queryset. If needed, the `meta` field on work items can be used as well.

However, this does not mean that an "undo" function will never be implemented. We just need a use case that really requires it, and we'll need to have another think about the exact impacts we want this to have.
