### ISSUE TITLE
[filters] Support word combinations in `SearchAnswersFilter`

### ISSUE THREAD

**Issue by open-dynaMIX** [projectcaluma/caluma#1927]
In (at least) one of our projects, there is a demand to search for word combinations. So that one could search for `"Foo Bar"` and only receive results that contain both words in the same order.

I've implemented this once in a DRF project and we would need to extract the search terms somewhere along those lines:

```python
    ...
    @staticmethod
    def _split(value):
        lex = shlex.shlex(value, posix=True)
        lex.whitespace_split = True
        lex.commenters = ""
        lex.quotes = '"'
        return [i.strip() for i in lex if i.strip()]

    def get_search_terms(self, request):
        params = request.query_params.get(self.search_param, "")
        params = params.replace("\x00", "")  # strip null characters
        try:
            return self._split(params)
        except ValueError as e:
            if e.args[0] == "No closing quotation":
                return self._split(f'{params}"')
    ...
```

This is potentially breaking, but I fail to see a usecase where it makes sense to search for literal quotation marks.

**Comment by winged** [comment]
I like the idea, especially since I think it would be the expected behaviour anyway, so this could even be classified as a bug fix :-)

I'd also not call it breaking, because searching for `"foo bar"` and expecting to get (`"foo thing"`, `something else and bar"`, across "unrelated" values in the same doc/case) is definitely not something I think people would do
