### ISSUE TITLE
Nested forms: queryset explosion

### ISSUE THREAD

**Issue by czosel** [projectcaluma/caluma#376]
I've looked into the performance issue we noticed around nested forms a bit and would like to share my findings:

There seems to be a queryset explosion when nested forms are queried - an example test case with some details is provided in #374. For further analysis you might get a head start by building up on #375, which sets up django-silk with caluma.

As suggested in https://github.com/graphql-python/graphene-django/issues/429, I've already tried `prefetch_related`, but until now with no luck. The performance improvements suggested in #229 do bring a slight improvement, but don't solve the actual queryset explosion. 

I hope that this helps with finding an actual solution for this issue.
/cc @sliverc @winged @open-dynaMIX

**Comment by sliverc** [comment]
@czosel 
As I have looked into this before some of my findings:

`prefetch_related` doesn't work because of how the Caluma visibility layer is designed where on each connection it can be defined what is visible. Hence a new queryset is called instead of using the prefetched one. This could potentially be worked around with [Prefetch](https://docs.djangoproject.com/en/2.1/ref/models/querysets/#django.db.models.Prefetch) but for this the query would need to be analyzed and the visibility layer redesigned. A fairly hard task.
This is not true for queries which single nodes and such can be optimized with `select_related`.

I wouldn't concentrate too much on the query explosion though but rather on the performance issue which I guess is your actual problem.

A few things I would do:
* as you have suggested integrate https://github.com/projectcaluma/caluma/pull/229/commits/8e39be8fa1094c8654b3d7b1cf8cb16b2fd92081 which gets rid of the count queries.
* potentially also integrate https://github.com/projectcaluma/caluma/pull/229/commits/95631c956c75b60257f09fcbcef1e3bc584bfd8a but only if it improves the performance significantly
* try to improve `select_related` for some nodes (overwrite get_queryset). Currently the default is simply calling `select_related` without any arguments. This will only pre-select the non null foreign keys. See [here](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#select-related) but you have some nullable foreign keys which might need to be select as well.
* potentially look at simplifying the GraphQL query. The example at https://github.com/projectcaluma/caluma/pull/374 looks pretty crazy :smile: It might make more sense from a frontend perspective to get the form and questions with one query (form could be cached as it doesn't change often) and the answers in  another query (which could be called more often).

**Comment by sliverc** [comment]
Closing this in favor of #476
