### ISSUE TITLE
Disable options

### ISSUE THREAD

**Issue by czosel** [projectcaluma/caluma#603]
I'm not sure what currently happens when options are removed (related: #339) - it would be nice if it was possible to "disable" options, meaning that documents which reference a disabled option still display correctly, but the disabled option is not available anymore for selection (e.g. in new documents).

/cc @sliverc @open-dynaMIX @kaldras @anehx

**Comment by open-dynaMIX** [comment]
I agree that already set options should never be removed. An alternative way would be to remove the option, if there is no reference to it in any document. Otherwise just disable it. This would not clutter the db in case of typos, etc (i.e. add a new option and remove it right after).

In any way, we need a `disabled` field (or similar) on the option.

**Comment by czosel** [comment]
:+1: Can you tell what happens currently?

**Comment by open-dynaMIX** [comment]
Ha, I just realized, we only store the `label` of the option in `Answer.value`. So removing the option itself will not manipulate any answer.

So my comment above can be ignored...

**Comment by open-dynaMIX** [comment]
This will be different, if we add an `OptionAnswer` as proposed [here](https://github.com/projectcaluma/caluma/issues/339#issuecomment-476575214).

**Comment by open-dynaMIX** [comment]
We need to rethink the whole Option handling, as proposed [here](https://github.com/projectcaluma/caluma/issues/339#issuecomment-476575214).

**Comment by sliverc** [comment]
Not to introduce `OptionAnswer` was that a choice answer could also be stored as integer if a api user desires. An `OptionAnswer` would restrict this.
Otherwise an `OptionAnswer` would give the possibility to expand the graph to directly get the option name from an answer without a second lookup.

Question is whether we want to support the first case or not.

**Comment by open-dynaMIX** [comment]
As discussed in person:

We will add a `is_archived`-field on the Option model.
