### ISSUE TITLE
History cleanup: force --keep parameter

### ISSUE THREAD

**Issue by winged** [projectcaluma/caluma#715]
@sbor23 correctly pointed out that we shouldn't allow the `cleanup_history` command to be run without the `--keep` argument:

> A little late to the party, but shouldn't the `keep` option be required without a default?
> As of now, if the argument has been forgotten, the whole history would be deleted, as the filter in L33 isn't applied.
> Or am I mistaken?

_Originally posted by @sbor23 in https://github.com/projectcaluma/caluma/pull/703_

**Comment by open-dynaMIX** [comment]
I don't have a problem changing this, just my 10¢:

I intentionally implemented it this way, because it's the most intuitive IMO. Management commands are often dangerous (see `flush`) and I think people using them are aware of that.

If we make `--keep` mandatory, we need to think of a way to completely drop all records. Something like `--keep "0 days"` seems clumsy and still leaves room for records to persist.

Another approach would be to rename `--dry` into something like `--do`, so without any argument the command just does a dry-run.

**Comment by sbor23** [comment]
Yes, by default running in "dry"-mode and only apply changes with `--force` sounds good.
