### ISSUE TITLE
Update python version

### ISSUE THREAD

**Issue by sbor23** [projectcaluma/caluma#773]
Now that 3.8 is out: Are there any particular reasons for staying on the `python:3.6` base image?
There are some goodies for developers especially like my precious `breakpoint()` which catches me off guard every time I try to use it in a <3.7 project.

So my proposal would be to bump the image to `python:3.7`, it will have bug fixes until 2023.
https://www.python.org/dev/peps/pep-0537/#and-beyond-schedule

**Comment by czosel** [comment]
We'd have to check if python 3.7 is available for our projects with non-docker deployments.

**Comment by open-dynaMIX** [comment]
One of the reasons we didn't switch to 3.7 already is, that not all dependencies had support for it. Before making this change, we have to make sure that this is not the case anymore.

**Comment by ganwell** [comment]
I accidentally tried 3.7: we have a lot of snapshot-tests, many of them break because in 3.7 the output is ordered different. I guess we have to check all that output and update the snapshots. Maybe we should check if jumping to 3.8 causes less problems. In theory dicts have a fixed order since Raymond Hettingers dicts improvements in 3.6, maybe something else is causing the problem.
