### ISSUE TITLE
Make label optional for saveFormQuestion

### ISSUE THREAD

**Issue by fkm** [projectcaluma/caluma#886]
As saveFormQuestion is also used to update a question it would be nice if the label could be optional.

An alternative would be to introduce a new Mutation: updateFormQuestion

[EDIT] Or maybe do it the way I do it in my personal projects. I have:
* create(ijnput)
* update(id, input)
* save(input)

The save method is just a wrapper that checks if the input contains an ID and chooses create or update accordingly.

**Comment by czosel** [comment]
In caluma, we chose a different design, where insert and update are handled by the same mutation ("upsert"), and I think there's no indication to move away from that. But maybe making the label optional for updates would be possible?

cc @open-dynaMIX

**Comment by fkm** [comment]
GraphQL doesn't allow for conditionally required fields.

What is the case for "upsert"?

**Comment by czosel** [comment]
It would be possible to make the field optional on the API and enforce it's presence during runtime for inserts. But when I think about why we went for "upsert" this doesn't seem like a good idea: The advantage of upsert is, apart from the smaller interface, the fact that you can execute a mutation that will create a desired state, without knowing about the current state on the server (is there a record already?). Making some fields conditionally required would break this property.

I think we rated this quality higher than the disadvantage of having to repeat properties in "update" mutations that one doesn't want to change, mainly because the information is usually already present in clients anyway. Also, this ensures records are saved in a "consistent" state. 

This is just how I think of it now, not sure if there were other motivations when this was decided.

**Comment by fkm** [comment]
I personally feel that it is more dangerous than helpful if we encourage just posting to the backend without knowing what's already there. To me, that doesn't feel right.

But let's add more stakeholders to this conversation:
@winged @kaldras @sbor23 @velrest @anehx @Yelinz @aziiee @JohnL17

**Comment by open-dynaMIX** [comment]
> I personally feel that it is more dangerous than helpful if we encourage just posting to the backend without knowing what's already there.

It's not, as the backend does all the needed checks. It's a different paradigm:

"Check what changes are needed and do them"

vs.

"Describe a desired state and let the backend decide what changes are needed"

Both paradigms have advantages and disadvantages, but as the decision to go with a "state-based" paradigm is already made and implemented everywhere, it's too late to change that IMO.

I'd prefer not mixing them, just for the sake of sparing a parameter in a mutation.

**Comment by winged** [comment]
I'm on the same line as @open-dynaMIX: Changing single attributes would, as it is in REST, require a separate call (PATCH vs POST). Since we don't do that here, we should always do the whole state.

Otherwise you'd somehow need to have the ability to differentiate between "set label to NULL" and "I'm not changing the label, whatever it is".

**Comment by czosel** [comment]
It would be possible to implement 3 kinds of mutations: Insert, Update, Upsert. But I agree with @open-dynaMIX - this would be overkill.

**Comment by fkm** [comment]
> we should always do the whole state

But we don't only the required part of the state.

**Comment by czosel** [comment]
Can you post an example?

**Comment by fkm** [comment]
**SaveFormInput**

Always included in the 'whole' state:
* slug
* name

The real whole state:
* slug
* name
* description
* meta
* isArchived
* isPublished

**Comment by open-dynaMIX** [comment]
Yes, that's how upserts work. It would be nice to have custom directives to define things like `field A is only required if field B is set`. But as long as that's not supported, the best will be to stick to our implementation.

**Comment by fkm** [comment]
Well. I am a pragmatist. So, I can accept that changing the strategy is not an option.

I just hope we revisit this topic before we implement another GraphQL API.
